### ISSUE TITLE
Suggestion: Move from php to node

### ISSUE THREAD

**Issue by mrodalgaard** [Cloudstek/alfred-atom#1]
Hi,

The reported error (see below) comes from seasons csonc CLI outputting trash in front of the parsed json, resulting in a `Control character error, possibly incorrectly encoded` error from `json_decode`. A solution is to strip those characters or substring from a fixed point. An even better solution though is to just use node.js in your workflow, since you already depend on the user having node installed and installing node modules.

Using npm modules [alfred-workflow-nodejs](https://github.com/giangvo/alfred-workflow-nodejs) to create workflows and [season](https://github.com/atom/season) to parse `projects.cson`.

If you are interested in this change I will send a major pull request.

```
[ERROR: alfred.workflow.input.scriptfilter] XML Parse Error 'The operation couldn’t be completed. (NSXMLParserErrorDomain error 4.)'. Row (null), Col (null): 'Document is empty' in XML:
Warning: Invalid argument supplied for foreach() in Command line code on line 13
<?xml version="1.0"?>
<items><item uid="atom56efec15c64427.61810899" arg="" valid="yes"><arg></arg><title>No projects found matching ''</title><subtitle></subtitle><icon type="fileicon">/Applications/Atom.app</icon></item></items>
```

**Comment by mdeboer** [comment]
That would be cool, it's very unfortunate that Atom uses CSON instead of just JSON to save a simple list. If it were JSON all would be a lot easier to process.

But go ahead, do a pull request and let me see! 👍

**Comment by mdeboer** [comment]
To come back to this. A switch to NodeJS would be a good option and I would love to make this happen. Yet at this time I have no time to make that happen. When I do, it would be nice to know what you think of it.
