### ISSUE TITLE
Error installing with npm

### ISSUE THREAD

**Issue by IanVS** [Cloudstek/alfred-atom#12]
I attempted to install using `npm i -g alfred-atom` as instructed in the readme, and I am getting the following error:

```
> alfred-atom@2.3.0 postinstall /Users/ianvs/.nvm/versions/node/v6.9.1/lib/node_modules/alfred-atom
> alfred-link

Error: Alfred preferences not found at location /Users/ianvs/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist
    at pathExists.then.exists (/Users/ianvs/.nvm/versions/node/v6.9.1/lib/node_modules/alfred-atom/node_modules/resolve-alfred-prefs/index.js:15:10)
```

Does this project only support Alfred 3?  I notice I have a `com.runningwithcrayons.Alfred-Preferences-2.plist` file, but not the `3` that it's looking for.

**Comment by mdeboer** [comment]
Hi @IanVS, yes this only supports Alfred v3 as this has many improvements over v2 which makes it so much easier to work with (as a programmer). So unfortunately there are no plans to support older versions.

I suggest you upgrade to v3 and make use of the many awesome workflows out there, including this one 😉  It's well worth it!

**Comment by IanVS** [comment]
Alright, cool.  I've been considering an upgrade anyway.

Maybe you could put that requirement in the README, to avoid confusion?
