### ISSUE TITLE
[2.3.2] Projects aren't listed

### ISSUE THREAD

**Issue by IanVS** [Cloudstek/alfred-atom#16]
Hi, 

With the new release, it seems that my projects are not being listed as they were with 2.3.0.  

2.3.2:
![image](https://user-images.githubusercontent.com/4616705/33891736-df28b7c6-df24-11e7-8bf8-a33dd13110a3.png)

2.3.0:
![image](https://user-images.githubusercontent.com/4616705/33891943-7612b1c8-df25-11e7-9528-84e2f1cb079a.png)

I'm happy to provide any other information that might help in debugging, but I'm not sure what would be useful.  Thanks!

**Comment by mdeboer** [comment]
Hi @IanVS, have you tried removing the workflow and reinstalling it? Please try using the release from the releases page: https://github.com/Cloudstek/alfred-atom/releases/tag/v2.3.2

If that doesn't work then please check for error messages or warnings in the debug log. You can open the debug log by opening Alfred, clicking on the workflow and clicking on the bug/spider icon in the top right corner. Leave this panel open and try to list your projects again. If anything goes wrong, you should see an error message.

But before you do, please try reinstalling first.

**Comment by mdeboer** [comment]
I'll close this due to inactivity.

**Comment by ashton** [comment]
The problem is that my nodejs binary is not in the default location, because it is installed by `asdf`, changing the default path on workflow object works for me :)

**Comment by mdeboer** [comment]
Ah yes that is correct. By default it assumes NodeJS was installed with Homebrew and is located at `/usr/local/bin/node`. However if you have installed NodeJS at a different path you can override this path with the `nodePath` (case sensitive) environment variable (add it when missing).

![screen shot 2018-04-26 at 14 48 02](https://user-images.githubusercontent.com/1171956/39306583-db7c5faa-4960-11e8-84c0-a43fbcf88a1b.png)

In future versions I will default to `node` in the current `$PATH` to avoid most issues like these.
