### ISSUE TITLE
Doesn't list Git projects

### ISSUE THREAD

**Issue by bdelaforest** [Cloudstek/alfred-atom#17]
In _Atom Project Manager_ package, an option allows to list all Git repositories found in Project Home, without needing to manually save them as project:

<img width="528" alt="project-manager-git-setting" src="https://user-images.githubusercontent.com/7151559/35186409-ffa85f02-fe13-11e7-8f6a-7c6fd21ea6dc.png">

Unfortunately, this workflow doesn't seem to list Git projects, as _Project Manager_ package do.

**Comment by mdeboer** [comment]
Currently it does not as it relies on the projects file (your saved projects). I will add it on the to-do list but I can't promise any ETA.

**Comment by danbohea** [comment]
Ooooooh, this would be real nice.

**Comment by mdeboer** [comment]
Note to self: Project home dir can be found in `config.cson -> *.core.projectHome`.

**Comment by mdeboer** [comment]
Okay I have implemented this in a version I'm about to release: v2.4.0. Please let me know if you have any issues.
