### ISSUE TITLE
Error Installing via NPM - 'Alfred preferences not found'

### ISSUE THREAD

**Issue by jamesarmenta** [Cloudstek/alfred-atom#18]
Unable to install because of the following error:
```Error: Alfred preferences not found at location /Users/myname/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist```

However using the 'Go to folder' command in finder I'm able to pull up the file using that path just fine. I don't believe it's an issue of permissions, as I ran the install using sudo. Any ideas?

**Comment by mdeboer** [comment]
This is an issue with [alfred-link](https://github.com/SamVerschueren/alfred-link) which in term uses [resolve-alfred-prefs](https://github.com/SamVerschueren/resolve-alfred-prefs). Please open an issue at [resolve-alfred-prefs](https://github.com/SamVerschueren/resolve-alfred-prefs).
