### ISSUE TITLE
Could not find theme file error

### ISSUE THREAD

**Issue by mdeboer** [Cloudstek/alfred-atom#19]
@mrodalgaard reported:

Could not find theme file error is received from Alfred when trying to use alfred-atom, probably because it is looking for a theme file that does not exist.

I also tried to add an empty json file at the specific location and that removed the error but alfred-atom output was still empty.

**Hugo version:** 1.2.0 used by alfred-atom 2.3.2
**Alfred version:** 3.6.1
**NodeJS version:** v9.5.0

**Exception / Stacktrace:**

```bash
[2018-04-09 15:43:23][STDERR: input.scriptfilter] Could not find theme file "/Users/martin/Library/Application Support/Alfred 3/Alfred.alfredpreferences/themes/theme.bundled.default/theme.json"
Could not find theme file "/Users/martin/Library/Application Support/Alfred 3/Alfred.alfredpreferences/themes/theme.bundled.default/theme.json"
```

**Comment by mrodalgaard** [comment]
Turns out it was me using the old syntax for atom projects. I added a PR #20 with info for anyone else experiencing this issue.
