### ISSUE TITLE
Error listing projects : Cannot find module '@babel/runtime/core-js/object/keys'

### ISSUE THREAD

**Issue by mcoeur** [Cloudstek/alfred-atom#21]
Hello,

I have the following error when I try to list the atom projects : Cannot find module '@babel/runtime/core-js/object/keys'

Here is a screenshot of the alfred debug console : 

![Screenshot 2019-03-12 at 07 19 41](https://user-images.githubusercontent.com/7251472/54178948-9ad65900-4497-11e9-931d-fc525db23d1f.png)

I installed the workflow through npm install.

Node version : 11.11.0 (latest stable version available today)

**Comment by mdeboer** [comment]
Odd, have you tried re-installing it? No errors during installation with NPM?

I'll have a look soon, see if I can reproduce it. In the meanwhile try downloading the workflow from the releases page [here](https://github.com/Cloudstek/alfred-atom/releases/download/v2.4.0/Atom.alfredworkflow) and make sure you remove the NPM installed version first before installing it by dragging it into the Workflow window of Alfred.

**Comment by mcoeur** [comment]
re-installing through npm didn't solve the problem.
However, after uninstalling and re-installing with the workflow file, it worked like a charm (I just had to adjust the nodePath env variable to get it to work with nvm).

Not sure why, but it was the right workaround for me, thanks a lot !
