### ISSUE TITLE
Doesn't work with whitespace in path name.

### ISSUE THREAD

**Issue by CalebGrove** [Cloudstek/alfred-atom#5]
Back when I was young and dumb, I named one of my primary working directories `Design Tools`.

I really need to change the name of that directory to remove the whitespace, but all the same, it's causing this workflow to fail. My guess is that it's not escaping whitespace in the path name, as what it's doing is trying to open two paths; `blah/blah/Design` **and** `Tools/blah/blah/`.

**Comment by mdeboer** [comment]
I just submitted a patch to the development branch 9d097a6c4a9985b2fe17b2de367c22cfa310f56b, does that fix it for you?

**Comment by CalebGrove** [comment]
Yep, that change fixes it, thanks @mrodalgaard!
