### ISSUE TITLE
Offer white icons for dark Alfred themes

### ISSUE THREAD

**Issue by danbohea** [Cloudstek/alfred-atom#8]
Really useful workflow here, thanks for this!

I use a dark Alfred theme and as such, the dark PNG files that you've included with this package don't look great. Would it be possible to include a set of white icons and a means to select them as a preferred option (or better yet use them automatically in dark Alfred themes)?

**Comment by danbohea** [comment]
Or failing that, offer an option to not display icons?

**Comment by mdeboer** [comment]
@danbohea thanks! In the next upcoming version I removed the bundled icons as I never really got them to work and when they did, I found them not very appealing. I think it's too much effort to include two icon sets or to paint the icon depending on the background colour.

Instead I improved the code that finds the icons and you'll be able to specify an absolute or relative path to the icon. I'm thinking of adding the option for an environment variable (configurable through Alfred) to specify a directory with the icons from your projects (e.g. ~/Projects/Icons/<project>.png). However, it always falls back to icon.png in your project folder(s).

I don't think it's possible to disable icons completely, but I'll need to take a look. If you have any ideas on how you want to manage your project icons, let me know. I find using a directory dedicated to project icons quite easy to work with.

**Comment by danbohea** [comment]
For those of us that don't want to manage a directory of icons for 1 Alfred extension, would it be possible to provide a further fallback whereby if _"icon.png in your project folder(s)"_ doesn't exist then we just use the Atom app icon?

**Comment by mdeboer** [comment]
Yes definitely, I think it does that by default when no icon is found. If you think of any other method of managing icons, please let me know so I can implement it 👍

**Comment by danbohea** [comment]
The only other thing that occurred to me was to use SVG rather than PNG, then colour could potentially be dynamically applied but I guess this all depends on Alfred and whether it even supports the use of SVG for icons.

**Comment by mdeboer** [comment]
@danbohea I checked and SVG seems to work perfectly and that would make it possible to change colour depending on the complexity of the icon. Would you like me to keep the icon set included and in SVG if I find a way to do this?

**Comment by danbohea** [comment]
Brilliant that sounds ideal! If we could also add a preference for white or dark icon colour then that should pretty much cover all use cases.

**Comment by mdeboer** [comment]
Deal 👍

**Comment by mdeboer** [comment]
Alright, I got octicon support working. It scans your Atom projects file for icons you use and converts those to PNG in the background. It will automatically recolour the icons depending on your theme and will rebuild the icons if you change it.

It'll be up for release soon, let me know what you think! 👍

**Comment by danbohea** [comment]
Just updated. Works great! :1st_place_medal:
