### ISSUE TITLE
Doesn't work if Node.js is installed with NVM

### ISSUE THREAD

**Issue by devert** [Cloudstek/alfred-atom#9]
I installed Node v7.10.0 with NVM. I get the following error when debugging the workflow.

```
[2017-05-08 16:09:42][ERROR: input.scriptfilter] Code 127: /Users/dennisevert/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Scripts/B8870D2A-C0B8-481A-9DCB-F0BF859DA5C1: line 1: /usr/local/bin/node: No such file or directory
```

**Comment by mdeboer** [comment]
My workflow assumes by default you installed Node using Homebrew. In your case you can adjust the path to NodeJS by setting the `nodePath` environment variable in the workflow like so:

![screenshot_2017-05-09_22_50_16_qznrnx](https://cloud.githubusercontent.com/assets/1171956/25872168/0fe1e6fa-350a-11e7-9cfc-dbfa2ebe45d2.png)

**Comment by devert** [comment]
Thanks @mdeboer. That makes sense. Note for other users that might come across this. I was also able to do run the following in a terminal to address this.

```
n=$(which node);n=${n%/bin/node}; chmod -R 755 $n/bin/*; sudo cp -r $n/{bin,lib,share} /usr/local
```

This copies whatever version of node you have active via nvm into the /usr/local/ directory and sets the permissions so that all users can access it.

If you ever want to change the version of node that's installed system wide, just do another nvm use vXX.XX.XX to switch your user's node to the version you want, and then re-run the above command to copy it to the system directory.
